name: Advent of Code 2024

on: [push]

jobs:
    build: 
        name: Test AOC24
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Checkout Logging submodule
              run: git submodule update --init --recursive
            
            - name: Compile
              env:
                CC: clang
                CXX: clang++
              run: |
                cmake -Bbuild -DAOC24_BUILD_TESTS=ON
                cmake --build build
            
            - name: Run Unit Tests
              run: |
                ./build/tests/AdventOfCode24_Test
                if [ $? -eq 0 ]; then
                    echo "Unit tests completed successfully"
                exit 0
                else
                    echo "Unit tests failed"
                    exit 1
                fi
            - name: Run Day 1 Solution
              run: ./build/solutions/day_1 solutions/data/day_1.txt
